nllb_eng_src_in_tatoeba = ['epo', 'est', 'eus', 'ewe', 'fao', 'fij', 'fin',
                           'fon', 'fra', 'fur', 'gla', 'gle', 'glg', 'grn', 'guj',
                           'hat', 'hau', 'heb', 'hin', 'hne', 'hun', 'hye', 'ibo',
                           'ilo', 'isl', 'ita', 'jav', 'jpn', 'kab', 'kac', 'kam',
                           'kan', 'kas', 'kat', 'kaz', 'kbp', 'kea', 'khm',
                           'kik', 'kin', 'kir', 'kmb', 'kon', 'kor', 'lao', 'lij',
                           'lim', 'lin', 'lit', 'lmo', 'ltz', 'lua', 'lug', 'luo',
                           'lus', 'mag', 'mai', 'mal', 'mar', 'mkd', 'mlt', 'mni',
                           'mos', 'mri', 'mya', 'nld', 'nso', 'nus', 'nya', 'oci',
                           'pag', 'pan', 'pap', 'pol', 'por', 'ron', 'run', 'rus',
                           'sag', 'san', 'sat', 'scn', 'shn', 'sin', 'slk', 'slv',
                           'smo', 'sna', 'snd', 'som', 'sot', 'spa', 'srd', 'ssw',
                           'sun', 'swe', 'szl', 'tam', 'tat', 'tel', 'tgk', 'tgl',
                           'tha', 'tir', 'tpi', 'tsn', 'tso', 'tuk', 'tum', 'tur',
                           'tzm', 'uig', 'ukr', 'umb', 'urd', 'vec', 'vie', 'war',
                           'wol', 'xho', 'yor', 'zho', 'zul']

all_nllb_langs = ['ace', 'ace', 'acm', 'acq', 'aeb', 'afr', 'ajp', 'aka', 'amh', 'apc', 'arb', 'ars', 'ary', 'arz',
                  'asm',
                  'ast', 'awa', 'ayr', 'azb', 'azj', 'bak', 'bam', 'ban', 'bem', 'ben', 'bho', 'bjn', 'bjn', 'bod',
                  'bos',
                  'bug', 'bul', 'cat', 'ceb', 'ces', 'cjk', 'ckb', 'crh', 'cym', 'dan', 'deu', 'dik', 'dyu', 'dzo',
                  'ell',
                  'eng', 'epo', 'est', 'eus', 'ewe', 'fao', 'pes', 'fij', 'fin', 'fon', 'fra', 'fur', 'fuv', 'gla',
                  'gle',
                  'glg', 'grn', 'guj', 'hat', 'hau', 'heb', 'hin', 'hne', 'hrv', 'hun', 'hye', 'ibo', 'ilo', 'ind',
                  'isl',
                  'ita', 'jav', 'jpn', 'kab', 'kac', 'kam', 'kan', 'kas', 'kas', 'kat', 'knc', 'knc', 'kaz', 'kbp',
                  'kea',
                  'khm', 'kik', 'kin', 'kir', 'kmb', 'kon', 'kor', 'kmr', 'lao', 'lvs', 'lij', 'lim', 'lin', 'lit',
                  'lmo',
                  'ltg', 'ltz', 'lua', 'lug', 'luo', 'lus', 'mag', 'mai', 'mal', 'mar', 'min', 'mkd', 'plt', 'mlt',
                  'mni',
                  'khk', 'mos', 'mri', 'zsm', 'mya', 'nld', 'nno', 'nob', 'npi', 'nso', 'nus', 'nya', 'oci', 'gaz',
                  'ory',
                  'pag', 'pan', 'pap', 'pol', 'por', 'prs', 'pbt', 'quy', 'ron', 'run', 'rus', 'sag', 'san', 'sat',
                  'scn',
                  'shn', 'sin', 'slk', 'slv', 'smo', 'sna', 'snd', 'som', 'sot', 'spa', 'als', 'srd', 'srp', 'ssw',
                  'sun',
                  'swe', 'swh', 'szl', 'tam', 'tat', 'tel', 'tgk', 'tgl', 'tha', 'tir', 'taq', 'taq', 'tpi', 'tsn',
                  'tso',
                  'tuk', 'tum', 'tur', 'twi', 'tzm', 'uig', 'ukr', 'umb', 'urd', 'uzn', 'vec', 'vie', 'war', 'wol',
                  'xho',
                  'ydd', 'yor', 'yue', 'zho', 'zho', 'zul']

all_tatoeba_langs = ['eng', 'gbm', 'heb', 'inh', 'kat', 'kum', 'lua', 'mlg', 'nds', 'ofs', 'pms', 'sag', 'snd', 'tet',
                     'tum', 'wln', 'enm', 'gcf', 'her', 'ipk', 'kau', 'kur', 'lug', 'mlt', 'nep', 'oji', 'pmy', 'sah',
                     'som', 'tgk', 'tur', 'wol', 'epo', 'gil', 'hif', 'iro', 'kaz', 'laa', 'luo', 'mni', 'new', 'ood',
                     'pnt', 'san', 'son', 'tgl', 'tvl', 'xal', 'est', 'gla', 'hil', 'isl', 'kbd', 'lad', 'lus', 'mnr',
                     'ngt', 'ori', 'pol', 'sat', 'sot', 'tha', 'tyj', 'xcl', 'eus', 'gle', 'hin', 'ita', 'kbh', 'lah',
                     'lut', 'mnw', 'ngu', 'orm', 'por', 'scn', 'spa', 'tig', 'tyv', 'xho', 'ewe', 'glg', 'hmn', 'ixl',
                     'kbp', 'lao', 'luy', 'moh', 'nhg', 'orv', 'pot', 'sco', 'sqi', 'tir', 'tzl', 'xmf', 'ext', 'glk',
                     'hmo', 'izh', 'kea', 'lat', 'lzz', 'mon', 'nhn', 'osp', 'ppk', 'ses', 'srd', 'tkl', 'tzm', 'yid',
                     'fao', 'glv', 'hne', 'jaa', 'kek', 'lav', 'mad', 'mos', 'nia', 'oss', 'ppl', 'sgn', 'srn', 'tlh',
                     'udm', 'yor', 'fas', 'gor', 'hoc', 'jam', 'kha', 'lbe', 'mag', 'mri', 'niu', 'ota', 'prg', 'sgs',
                     'ssw', 'tly', 'uig', 'yua', 'fij', 'gos', 'hrx', 'jav', 'khm', 'ldn', 'mah', 'msa', 'nld', 'pag',
                     'pus', 'shi', 'stq', 'tmh', 'ukr', 'zap', 'fil', 'got', 'hsb', 'jbo', 'kik', 'lez', 'mai', 'mus',
                     'nlv', 'pai', 'quc', 'shn', 'sun', 'tmr', 'umb', 'zea', 'fin', 'grc', 'hun', 'jdt', 'kin', 'lfn',
                     'mal', 'mvv', 'nnb', 'pal', 'que', 'shs', 'sux', 'toi', 'urd', 'zgh', 'fkv', 'grn', 'hus', 'jiv',
                     'kir', 'lij', 'mam', 'mwl', 'nog', 'pam', 'qya', 'shy', 'swa', 'tok', 'usp', 'zha', 'fon', 'gsw',
                     'hye', 'jpa', 'kjh', 'lim', 'mar', 'mya', 'non', 'pan', 'rap', 'sin', 'swe', 'ton', 'uzb', 'zho',
                     'fra', 'guc', 'hyw', 'jpn', 'kmb', 'lin', 'mdf', 'myv', 'nor', 'pap', 'rhg', 'sjn', 'swg', 'tpi',
                     'vec', 'zul', 'frm', 'guj', 'iba', 'kaa', 'kok', 'lit', 'meh', 'mzn', 'nov', 'pau', 'rif', 'slk',
                     'syl', 'tpw', 'ven', 'zza', 'frp', 'guw', 'ibo', 'kab', 'kom', 'liv', 'mfe', 'nah', 'nqo', 'pck',
                     'roh', 'slv', 'syr', 'trs', 'vie', 'frr', 'hai', 'ido', 'kac', 'kon', 'lkt', 'mgm', 'nap', 'nso',
                     'pcm', 'rom', 'sma', 'szl', 'trv', 'vls', 'fry', 'hat', 'iii', 'kal', 'kor', 'lld', 'mic', 'nau',
                     'nst', 'pdc', 'ron', 'sme', 'tah', 'tsn', 'vol', 'ful', 'hau', 'iku', 'kam', 'krc', 'lmo', 'mik',
                     'nav', 'nus', 'pfl', 'rue', 'sml', 'tam', 'tso', 'vot', 'fur', 'haw', 'ile', 'kan', 'krl', 'lou',
                     'miq', 'nbl', 'nya', 'phn', 'run', 'smn', 'tat', 'tsz', 'wae', 'gag', 'hbo', 'ilo', 'kar', 'ksh',
                     'lrc', 'mix', 'nch', 'oar', 'pih', 'rup', 'smo', 'tcy', 'tts', 'wal', 'gbi', 'hbs', 'ina', 'kas',
                     'kua', 'ltz', 'mkd', 'nde', 'oci', 'pli', 'rus', 'sna', 'tel', 'tuk', 'war']


